name: Build Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pytest
      continue-on-error: false

    - name: Debug - Check Python version and environment
      run: |
        python --version
        pip list
        echo "Operating system: $RUNNER_OS"
        uname -a  # For additional info on the system in Ubuntu/macOS

    - name: Run tests
      run: |
        python -m pytest --maxfail=5 --disable-warnings
